version: '3.8'

services:
  # Agent 1 - Development
  agent-dev-01:
    build: .
    container_name: iot-agent-dev-01
    restart: unless-stopped
    environment:
      - DEVICE_ID=1
      - DEVICE_NAME=dev-pi-01
      - BACKEND_URL=http://host.docker.internal:8000  # Kết nối với backend local
      - DOCKER_IMAGE=taipham2710/agent:latest
      - HEARTBEAT_INTERVAL=30   # Nhanh hơn cho development
      - LOG_INTERVAL=10         # Log thường xuyên
      - UPDATE_CHECK_INTERVAL=60
      - LOG_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Cho macOS/Windows

  # Agent 2 - Development
  agent-dev-02:
    build: .
    container_name: iot-agent-dev-02
    restart: unless-stopped
    environment:
      - DEVICE_ID=2
      - DEVICE_NAME=dev-pi-02
      - BACKEND_URL=http://host.docker.internal:8000
      - DOCKER_IMAGE=taipham2710/agent:latest
      - HEARTBEAT_INTERVAL=30
      - LOG_INTERVAL=10
      - UPDATE_CHECK_INTERVAL=60
      - LOG_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Agent 3 - Development (sensor simulation)
  agent-dev-03:
    build: .
    container_name: iot-agent-dev-03
    restart: unless-stopped
    environment:
      - DEVICE_ID=3
      - DEVICE_NAME=dev-pi-sensor
      - BACKEND_URL=http://host.docker.internal:8000
      - DOCKER_IMAGE=taipham2710/agent:latest
      - HEARTBEAT_INTERVAL=15   # Rất nhanh cho testing
      - LOG_INTERVAL=5          # Log liên tục
      - UPDATE_CHECK_INTERVAL=30
      - LOG_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway" 